# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: xcx01_server
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xxx.*.entity
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出到控制台
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 结合logback输出到日志文件
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

wx:
  jscode2session_url: https://api.weixin.qq.com/sns/jscode2session
  appid: wx736f2ce46f1621e5
  secret: 9acdec9971a39e21bf20027cbd3d61e5
  grant_type: authorization_code


